server:
  servlet:
    context-path: "/client/"
  error:
    include-stacktrace: never
    include-message: never
spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    url: jdbc:postgresql://localhost:5432/
    schemas: postgres
    user: postgres
    password: postgres